spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    database-platform: org.hibernate.dialect.H2Dialect


  jpa:
    properties:
      hibernate:
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console